require('angular')
$ = jQuery = require('jquery')
require('angular-ui-bootstrap')
require('angular-ui-router-title')
require('angular-ui-router')
require('angularjs-color-picker')
tinycolor = require('tinycolor2')
require('bootstrap')
Dropzone = require('dropzone')
require('jquery-ui-bundle')
require('jquery-ui-touch-punch')
io = require('socket.io-client')
