// Generated by CoffeeScript 1.9.3
var Message, Picture, api, db, express, fs, messageSchema, mongoose, pictureSchema;

fs = require('fs');

express = require('express');

api = express.Router();

mongoose = require('mongoose');

db = require('../Utilities/DB');

messageSchema = new mongoose.Schema({
  timestamp: Number,
  user: String,
  content: String
});

Message = mongoose.model('message', messageSchema);

pictureSchema = new mongoose.Schema({
  file: Buffer,
  x: Number,
  y: Number,
  fileName: Number
});

Picture = mongoose.model('picture', pictureSchema);

api.post('/api/message', function(req, res) {
  var content, message, timestamp, user;
  timestamp = (new Date()).getTime();
  user = req.query.user;
  content = req.query.content;
  message = new Message({
    timestamp: timestamp,
    user: user,
    content: content
  });
  return message.save(function(err, message) {
    if (err) {
      res.sendStatus(500);
      throw err;
    } else {
      return res.sendStatus(200);
    }
  });
});

api.get('/api/messages', function(req, res) {
  return Message.find({}).sort('timestamp').exec(function(err, messages) {
    if (err) {
      return res.sendStatus(500);
    } else {
      return res.json(messages);
    }
  });
});

api.get('/api/message', function(req, res) {
  var lastMessageId;
  lastMessageId = req.query.lastMessageId ? req.query.lastMessageId : -1;
  return Message.find({}).sort('timestamp').exec(function(err, messages) {
    var i, len, message;
    if (err) {
      res.sendStatus(500);
      throw err;
    } else {
      for (i = 0, len = messages.length; i < len; i++) {
        message = messages[i];
        if (message.timestamp > lastMessageId) {
          res.json(message);
          return;
        }
      }
      return res.sendStatus(404);
    }
  });
});

api.post('/api/picture', function(req, res) {
  var fileName, fullFilePath, x, y;
  fileName = (new Date()).getTime();
  x = req.query.x;
  y = req.query.y;
  fullFilePath = __dirname + '/' + fileName + Math.floor(Math.random() * 20000);
  return req.pipe(fs.createWriteStream(fullFilePath)).on('finish', function() {
    var picture;
    picture = new Picture({
      fileName: fileName,
      x: x,
      y: y,
      file: fs.readFileSync(fullFilePath)
    });
    return picture.save(function(err, picture) {
      if (err) {
        res.sendStatus(500);
        throw err;
      } else {
        return res.sendStatus(201);
      }
    }).then(function() {
      return fs.unlinkSync(fullFilePath);
    });
  });
});

api.get('/api/picture', function(req, res) {
  var lastFile;
  lastFile = req.query.lastFile ? req.query.lastFile : -1;
  return Picture.find({}).sort('fileName').exec(function(err, files) {
    var file, i, len;
    if (err) {
      res.sendStatus(500);
      throw err;
    } else {
      for (i = 0, len = files.length; i < len; i++) {
        file = files[i];
        if (file.fileName > lastFile) {
          res.set({
            'Content-Type': 'image/jpeg'
          });
          res.set({
            'fileName': file.fileName
          });
          res.set({
            'x': file.x
          });
          res.set({
            'y': file.y
          });
          res.send(file.file);
          return;
        }
      }
      return res.sendStatus(404);
    }
  });
});

module.exports = api;
