// Generated by CoffeeScript 1.9.3
var Message, api, db, express, fs, messageSchema, mongoose;

fs = require('fs');

express = require('express');

api = express.Router();

mongoose = require('mongoose');

db = require('../Utilities/DB');

messageSchema = new mongoose.Schema({
  timestamp: Number,
  user: String,
  content: String
});

Message = mongoose.model('message', messageSchema);

api.post('/api/message', function(req, res) {
  var content, message, timestamp, user;
  timestamp = (new Date()).getTime();
  user = req.query.user;
  content = req.query.content;
  message = new Message({
    timestamp: timestamp,
    user: user,
    content: content
  });
  return message.save(function(err, message) {
    if (err) {
      res.sendStatus(500);
      throw err;
    } else {
      return res.sendStatus(200);
    }
  });
});

api.get('/api/messages', function(req, res) {
  return Message.find({}).sort('timestamp').exec(function(err, messages) {
    if (err) {
      return res.sendStatus(500);
    } else {
      return res.json(messages);
    }
  });
});

module.exports = api;
