// Generated by CoffeeScript 1.9.3
var Group, Item, User, fs, isLoggedIn, multer, upload;

fs = require('fs');

multer = require('multer');

upload = multer({
  dest: 'uploads/'
});

Item = require('../models/Item');

User = require('../models/User');

Group = require('../models/Group');

isLoggedIn = function(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  } else {
    return res.sendStatus(500);
  }
};

module.exports = function(app, passport) {
  var io;
  io = app.io;
  io.on('connection', function(socket) {
    socket.on('groupConnect', function(user, group) {
      socket.join(group);
      socket.username = user;
      socket.group = group;
      return socket.emit('setupComplete');
    });
    socket.on('getInitialMessages', function() {
      return Group.findOne({
        name: socket.group
      }).select('messages').sort('timestamp').exec(function(err, data) {
        if (data && !err) {
          return socket.emit('initialMessages', data.messages);
        }
      });
    });
    socket.on('postNewMessage', function(messageContent) {
      var newMessage;
      newMessage = {
        timestamp: (new Date()).getTime(),
        user: socket.username,
        content: messageContent
      };
      return Group.update({
        name: socket.group
      }, {
        $push: {
          'messages': newMessage
        }
      }, function(err) {
        if (!err) {
          return io.sockets["in"](socket.group).emit('newMessage', newMessage);
        }
      });
    });
    socket.on('postRemoveMessage', function(timestamp) {
      return Group.update({
        name: socket.group
      }, {
        $pull: {
          'messages': {
            timestamp: timestamp
          }
        }
      }, function(err) {
        if (!err) {
          return io.sockets["in"](socket.group).emit('removeMessage', timestamp);
        }
      });
    });
    socket.on('getInitialItems', function() {
      return Item.find({
        group: socket.group
      }).select('fileName type x y text').sort('fileName').exec(function(err, itemsInfo) {
        var i, itemInfo, len, results;
        if (!err) {
          results = [];
          for (i = 0, len = itemsInfo.length; i < len; i++) {
            itemInfo = itemsInfo[i];
            results.push(socket.emit('newItem', itemInfo));
          }
          return results;
        }
      });
    });
    return socket.on('updateItemLocation', function(fileName, newX, newY) {
      return Item.findOne({
        fileName: fileName
      }).select('fileName x y').exec(function(err, item) {
        if (item && !err) {
          item.x = newX;
          item.y = newY;
          item.save();
          return io.sockets["in"](socket.group).emit('updateItem', item);
        }
      });
    });
  });
  app.get('/api/groups', isLoggedIn, function(req, res) {
    var err, username;
    username = req.user.username;
    try {
      return User.findOne({
        username: username
      }, function(err1, user) {
        if (err1) {
          throw err1;
        }
        return res.json(user.groups);
      });
    } catch (_error) {
      err = _error;
      return res.sendStatus(500);
    }
  });
  app.post('/api/newGroup', isLoggedIn, function(req, res) {
    var err, newGroupName, username;
    username = req.user.username;
    newGroupName = req.query.newGroupName;
    try {
      return Group.find({
        name: newGroupName
      }, function(err1, groups) {
        var newGroup;
        if (err1) {
          throw err1;
        }
        if (groups.length > 0) {
          return res.sendStatus(409);
        } else {
          newGroup = new Group({
            name: newGroupName
          });
          return newGroup.save(function(err2, group) {
            if (err2) {
              throw err2;
            }
            return User.findOne({
              username: username
            }, function(err3, user) {
              if (err3) {
                throw err3;
              }
              user.groups.push(newGroupName);
              return user.save(function(err4, user2) {
                if (err4) {
                  throw err4;
                }
                return res.json(newGroupName);
              });
            });
          });
        }
      });
    } catch (_error) {
      err = _error;
      return res.sendStatus(500);
    }
  });
  app.post('/api/text', isLoggedIn, function(req, res) {
    var err, fileName, group, item, text, type, x, y;
    fileName = (new Date()).getTime();
    group = req.query.group;
    type = 'text';
    x = 1;
    y = 1;
    text = req.body.text;
    try {
      item = new Item({
        group: group,
        fileName: fileName,
        type: type,
        x: x,
        y: y,
        text: text
      });
      return item.save(function(err1, file) {
        var newItem;
        if (err1) {
          throw err1;
        }
        newItem = {
          fileName: fileName,
          type: type,
          x: x,
          y: y,
          text: text
        };
        io.sockets["in"](group).emit('newItem', newItem);
        return res.sendStatus(201);
      });
    } catch (_error) {
      err = _error;
      return res.sendStatus(500);
    }
  });
  app.post('/api/fileUpload', isLoggedIn, upload.single('file'), function(req, res) {
    var fileName, fullFilePath, group, item, type, x, y;
    fileName = (new Date()).getTime();
    group = req.query.group;
    type = req.file.mimetype;
    x = req.query.x;
    y = req.query.y;
    fullFilePath = req.file.path;
    item = new Item({
      fileName: fileName,
      group: group,
      type: type,
      x: x,
      y: y,
      file: fs.readFileSync(fullFilePath)
    });
    return item.save(function(err1) {
      var newItem;
      if (!err1) {
        newItem = {
          fileName: fileName,
          type: type,
          x: x,
          y: y
        };
        io.sockets["in"](group).emit('newItem', newItem);
      }
      res.redirect('back');
      return fs.unlinkSync(fullFilePath);
    });
  });
  return app.get('/api/picture', isLoggedIn, function(req, res) {
    var err;
    try {
      return Item.findOne({
        fileName: req.query.fileToGet,
        group: req.query.groupName
      }).select('file type').exec(function(err, file) {
        var b;
        if (!file || err) {
          throw err;
        }
        res.set({
          'Content-Type': file.type
        });
        b = file.file;
        return res.send(b);
      });
    } catch (_error) {
      err = _error;
      return res.sendStatus(500);
    }
  });
};
