// Generated by CoffeeScript 1.9.3
var DB, api, express, router;

express = require('express');

router = express.Router();

api = require('./api');

router.use(api);

DB = require('../Utilities/DB');

router.get('/messages', function(req, res, next) {
  return res.render('messages', {
    title: "Messages"
  });
});

router.get('*', function(req, res, next) {
  return res.render('index', {
    title: 'Runway'
  });
});

module.exports = router;
