<<<<<<< HEAD
// Generated by CoffeeScript 1.10.0
var DB, express, router;
=======
// Generated by CoffeeScript 1.9.3
var DB, api, express, router;
>>>>>>> 23108b5eb97e7f09000f46696f089d0abfad40b2

express = require('express');

router = express.Router();

api = require('./api');

router.use(api);

DB = require('../Utilities/DB');

<<<<<<< HEAD
router.get('/workspace', function(req, res, next) {
  return res.render('workspace', {
    title: 'Workspace'
  });
});

router.get('/letters', function(req, res, next) {
  return res.sendfile('./public/letters.json');
=======
router.get('/messages', function(req, res, next) {
  return res.render('messages', {
    title: "Messages"
  });
>>>>>>> 23108b5eb97e7f09000f46696f089d0abfad40b2
});

router.get('*', function(req, res, next) {
  return res.render('index', {
    title: 'Runway'
  });
});

module.exports = router;
