// Generated by CoffeeScript 1.10.0
var DB, express, router;

express = require('express');

router = express.Router();

DB = require('../Utilities/DB');

router.get('/workspace', function(req, res, next) {
  return res.render('workspace', {
    title: 'Workspace'
  });
});

router.get('/letters', function(req, res, next) {
  return res.sendfile('./public/letters.json');
});

router.get('*', function(req, res, next) {
  return res.render('index', {
    title: 'Runway'
  });
});

module.exports = router;
