// Generated by CoffeeScript 1.9.3
var express;

express = require('express');

module.exports = function(isLoggedIn) {
  var partialRouter;
  partialRouter = express.Router();
  partialRouter.get('/groups', isLoggedIn, function(req, res) {
    return res.render('groups');
  });
  partialRouter.get('/manage', isLoggedIn, function(req, res) {
    return res.render('manage');
  });
  return partialRouter;
};
