// Generated by CoffeeScript 1.10.0
(function() {
  var express;

  express = require('express');

  module.exports = function(passport, io) {
    var apiRouter, pageRouter, router;
    router = express.Router();
    apiRouter = require('./apiRouter')(passport, io);
    pageRouter = require('./pageRouter')(passport);
    router.use('/api', apiRouter);
    router.use(pageRouter);
    return router;
  };

}).call(this);
