// Generated by CoffeeScript 1.9.3
var express;

express = require('express');

module.exports = function(passport, io) {
  var apiRouter, pageRouter, router;
  router = express.Router();
  apiRouter = require('./apiRouter')(passport, io);
  pageRouter = require('./pageRouter')(passport);
  router.use('/api', apiRouter);
  router.use(pageRouter);
  return router;
};
