// Generated by CoffeeScript 1.9.3
var groupSchema, mongoose;

mongoose = require('mongoose');

groupSchema = new mongoose.Schema({
  name: String
});

module.exports = mongoose.model('group', groupSchema);
