// Generated by CoffeeScript 1.9.3
var bcrypt, mongoose, userSchema;

mongoose = require('mongoose');

bcrypt = require('bcrypt-nodejs');

userSchema = new mongoose.Schema({
  username: String,
  password: String,
  groups: []
});

userSchema.methods.generateHash = function(password) {
  return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
};

userSchema.methods.validPassword = function(password) {
  return bcrypt.compareSync(password, this.password);
};

module.exports = mongoose.model('user', userSchema);
